export const APP_VERSION = import.meta.env.VITE_APP_VERSION ?? "0.1.0";

export const INVENTORY_HEADERS = [
  "App ID",
  "Date Purchased",
  "Quantity",
  "Player",
  "Year",
  "Set",
  "Variation",
  "Number",
  "Category",
  "Condition",
  "Investment",
  "Estimated Value",
  "Ladder ID",
  "Notes",
  "Date Sold",
  "Sold Price",
  "Image",
  "Created At",
  "Updated At",
  "Last Imported At"
] as const;

export const CARD_LADDER_HEADERS = [
  "Date Purchased",
  "Quantity",
  "Player",
  "Year",
  "Set",
  "Variation",
  "Number",
  "Category",
  "Condition",
  "Investment",
  "Estimated Value",
  "Ladder ID",
  "Notes",
  "Date Sold",
  "Sold Price",
  "Image"
] as const;

export const REQUIRED_CARD_LADDER_HEADERS = [
  "Date Purchased",
  "Player",
  "Year",
  "Set",
  "Category",
  "Condition",
  "Investment"
] as const;

export const CARD_LADDER_CATEGORIES = [
  "Basketball",
  "Baseball",
  "Football",
  "Hockey",
  "Soccer",
  "Tennis",
  "Wrestling",
  "Racing",
  "Golf",
  "Boxing",
  "UFC/MMA",
  "Pokemon",
  "Magic",
  "Metazoo",
  "Yugioh",
  "Fortnite",
  "Dragonballz",
  "Entertainment",
  "Swimming",
  "Softball",
  "PopCulture",
  "Flesh and Blood"
] as const;

export const CARD_LADDER_CONDITIONS = [
  "BGS 10 Black",
  "SGC 10 Pristine",
  "CGC 10 Perfect",
  "PSA 10",
  "BGS 10",
  "SGC 10",
  "CGC 10",
  "PSA 10/Auto 10",
  "PSA 10/Auto 9",
  "PSA 10/Auto 8",
  "BGS 10/Auto 10",
  "SGC 10/Auto 10",
  "BGS 9.5",
  "SGC 9.5",
  "CGC 9.5",
  "BGS 9.5/Auto 10",
  "SGC 9.5/Auto 10",
  "BGS 9.5/Auto 9",
  "PSA 9",
  "BGS 9",
  "SGC 9",
  "CGC 9",
  "PSA 9/Auto 10",
  "PSA 9/Auto 9",
  "PSA 9/Auto 8",
  "BGS 9/Auto 10",
  "BGS 9/Auto 9",
  "SGC 9/Auto 10",
  "Raw",
  "PSA 8.5",
  "BGS 8.5",
  "CGC 8.5",
  "SGC 8.5",
  "BGS 8.5/Auto 10",
  "PSA 8",
  "BGS 8",
  "SGC 8",
  "CGC 8",
  "PSA 8/Auto 10",
  "PSA 8/Auto 9",
  "PSA 8/Auto 8",
  "BGS 8/Auto 10",
  "PSA 7.5",
  "BGS 7.5",
  "SGC 7.5",
  "CGC 7.5",
  "BGS 7.5/Auto 10",
  "PSA 7",
  "BGS 7",
  "SGC 7",
  "CGC 7",
  "PSA 7/Auto 10",
  "BGS 7/Auto 10",
  "PSA 6.5",
  "BGS 6.5",
  "SGC 6.5",
  "CGC 6.5",
  "BGS 6.5/Auto 10",
  "PSA 6",
  "BGS 6",
  "SGC 6",
  "CGC 6",
  "PSA 6/Auto 10",
  "BGS 6/Auto 10",
  "PSA 5.5",
  "BGS 5.5",
  "SGC 5.5",
  "CGC 5.5",
  "PSA 5",
  "BGS 5",
  "SGC 5",
  "CGC 5",
  "PSA 4.5",
  "BGS 4.5",
  "SGC 4.5",
  "CGC 4.5",
  "PSA 4",
  "BGS 4",
  "SGC 4",
  "CGC 4",
  "PSA 3.5",
  "BGS 3.5",
  "SGC 3.5",
  "CGC 3.5",
  "PSA 3",
  "BGS 3",
  "SGC 3",
  "CGC 3",
  "PSA 2.5",
  "BGS 2.5",
  "SGC 2.5",
  "CGC 2.5",
  "PSA 2",
  "BGS 2",
  "SGC 2",
  "CGC 2",
  "PSA 1.5",
  "BGS 1.5",
  "SGC 1.5",
  "CGC 1.5",
  "PSA 1",
  "BGS 1",
  "SGC 1",
  "CGC 1",
  "PSA Authentic",
  "BGS Authentic",
  "SGC Authentic",
  "PSA Authentic Altered",
  "PSA Authentic/Auto 10",
  "Encased",
  "Sealed",
  "HGA 10",
  "HGA 9.5",
  "HGA 9",
  "HGA 8.5",
  "HGA 8",
  "HGA 7.5",
  "HGA 7",
  "HGA 6.5",
  "HGA 6",
  "HGA 5.5",
  "HGA 5",
  "HGA 4.5",
  "HGA 4",
  "HGA 3.5",
  "HGA 3",
  "HGA 2.5",
  "HGA 2",
  "HGA 1.5",
  "HGA 1",
  "CSG 10 Perfect",
  "CSG 10",
  "CSG 9.5",
  "CSG 9",
  "CSG 8.5",
  "CSG 8",
  "CSG 7.5",
  "CSG 7",
  "CSG 6.5",
  "CSG 6",
  "CSG 5.5",
  "CSG 5",
  "CSG 4.5",
  "CSG 4",
  "CSG 3.5",
  "CSG 3",
  "CSG 2.5",
  "CSG 2",
  "CSG 1.5",
  "CSG 1",
  "BVG 10",
  "BVG 9.5",
  "BVG 9",
  "BVG 8.5",
  "BVG 8",
  "BVG 7.5",
  "BVG 7",
  "BVG 6.5",
  "BVG 6",
  "BVG 5.5",
  "BVG 5",
  "BVG 4.5",
  "BVG 4",
  "BVG 3.5",
  "BVG 3",
  "BVG 2.5",
  "BVG 2",
  "BVG 1.5",
  "BVG 1"
] as const;
